name: speech_synthesis
description: Aizere

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For state management Provider
  provider: ^5.0.0
  # DI
  get_it: ^5.0.5
  # Reactive dart
  rxdart: ^0.27.1
  # For server request
  dio: ^4.0.0
  http: ^0.13.3
  # Used for compare two objects
  equatable: ^1.2.5
  # Save to some data to local cache
  shared_preferences: ^2.0.8
  # Play to audio file
  just_audio: ^0.8.0
  # Application logo changer
  flutter_launcher_icons: ^0.9.0

  # UI
  shimmer: ^1.1.2
  flutter_svg: ^0.20.0-nullsafety.3
  flutter_screenutil: ^5.0.0+2
  system_alert_window: ^0.4.4
  path_provider: ^2.0.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - assets/fonts/
    - assets/others/
    - assets/audio/


  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-BlackItalic.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-BoldItalic.ttf
        - asset: assets/fonts/Raleway-ExtraBoldItalic.ttf
        - asset: assets/fonts/Raleway-ExtraBold.ttf
        - asset: assets/fonts/Raleway-ExtraBoldItalic.ttf
        - asset: assets/fonts/Raleway-ExtraLightItalic.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
        - asset: assets/fonts/Raleway-LightItalic.ttf
        - asset: assets/fonts/Raleway-MediumItalic.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
        - asset: assets/fonts/Raleway-SemiBoldItalic.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
        - asset: assets/fonts/Raleway-ThinItalic.ttf